package nodes_test

import (
	"context"
	"encoding/base32"
	"testing"

	"christiangeorgelucas/otp-tools/nodes"

	gen "christiangeorgelucas/otp-tools/gen"
)

// Independent-oracle test: RFC 4648 §10's own base32 test vector
// ("fooba" -> "MZXW6YTB"), hand-published by the encoding's own spec,
// exercised here via the deterministic entropy path.
func TestGenerateRandomSecret_RFC4648Vector(t *testing.T) {
	ctx := context.Background()
	ax := newTestContext(t)

	got, err := nodes.GenerateRandomSecret(ctx, ax, &gen.GenerateRandomSecretInput{
		ByteLength: 5,
		Entropy:    []byte("fooba"),
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if got.Error != "" {
		t.Fatalf("node error: %s", got.Error)
	}
	if got.SecretBase32 != "MZXW6YTB" {
		t.Errorf("secret_base32=%q, want %q (RFC 4648 §10)", got.SecretBase32, "MZXW6YTB")
	}
	if got.ByteLength != 5 {
		t.Errorf("byte_length=%d, want 5", got.ByteLength)
	}
}

func TestGenerateRandomSecret_DefaultsTo20BytesAndIsRandom(t *testing.T) {
	ctx := context.Background()
	ax := newTestContext(t)

	got1, err := nodes.GenerateRandomSecret(ctx, ax, &gen.GenerateRandomSecretInput{})
	if err != nil || got1.Error != "" {
		t.Fatalf("err=%v nodeErr=%s", err, got1.Error)
	}
	if got1.ByteLength != 20 {
		t.Errorf("byte_length=%d, want 20 (default)", got1.ByteLength)
	}
	if got1.SecretBase32 == "" {
		t.Fatalf("secret_base32 is empty")
	}

	got2, err := nodes.GenerateRandomSecret(ctx, ax, &gen.GenerateRandomSecretInput{})
	if err != nil || got2.Error != "" {
		t.Fatalf("err=%v nodeErr=%s", err, got2.Error)
	}
	if got1.SecretBase32 == got2.SecretBase32 {
		t.Errorf("two CSPRNG-backed calls returned the same secret — randomness is broken")
	}
}

// Payload size is the platform's job, not the node's (ADR: node = pure
// input->output function). This exercises a byte_length far larger than the
// package's old, now-removed 256-byte cap and asserts the node handles it
// without crashing, returning that many freshly generated bytes.
func TestGenerateRandomSecret_LargeByteLengthDoesNotCrash(t *testing.T) {
	ctx := context.Background()
	ax := newTestContext(t)
	const want = 100000
	got, err := nodes.GenerateRandomSecret(ctx, ax, &gen.GenerateRandomSecretInput{ByteLength: want})
	if err != nil {
		t.Fatalf("unexpected Go error: %v", err)
	}
	if got.Error != "" {
		t.Fatalf("unexpected node error for a large byte_length: %s", got.Error)
	}
	if got.ByteLength != want {
		t.Errorf("ByteLength = %d, want %d", got.ByteLength, want)
	}
	decoded, err := base32.StdEncoding.WithPadding(base32.NoPadding).DecodeString(got.SecretBase32)
	if err != nil {
		t.Fatalf("failed to decode returned base32 secret: %v", err)
	}
	if len(decoded) != want {
		t.Errorf("decoded secret is %d bytes, want %d", len(decoded), want)
	}
}

func TestGenerateRandomSecret_EntropyLengthMismatchIsRejected(t *testing.T) {
	ctx := context.Background()
	ax := newTestContext(t)
	got, err := nodes.GenerateRandomSecret(ctx, ax, &gen.GenerateRandomSecretInput{
		ByteLength: 10,
		Entropy:    []byte("tooshort"),
	})
	if err != nil {
		t.Fatalf("unexpected Go error: %v", err)
	}
	if got.Error == "" {
		t.Errorf("want a structured error for entropy length != byte_length, got none")
	}
}
